version: 2
jobs:
  build_push:
    docker:
      - image: ubuntu/18.04
        environment:
          TAG: v${CIRCLE_BUILD_NUM} 

    steps:
      - checkout

      - run:
          name: Install make
          command: |
            apt-get update
            apt-get install make

      - setup_remote_docker:
          version: 17.06.0-ce
          reusable: false
      
      - run:
          name: Login to docker hub
          shell: /bin/bash
          command: |
            make login

      - run:
          name: Build docker container
          shell: /bin/bash
          command: |
            make build

      - run:
          name: Push docker container
          shell: /bin/bash
          command: |
            make push


  install:
    docker:
      - image: google/cloud-sdk
        environment:
          TAG: v${CIRCLE_BUILD_NUM} 

    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
 
      - run:
          name: Install make
          command: |
            apt-get update
            apt-get install make

      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh

      - run:
          name: Generate kubeconfig
          shell: /bin/bash
          command: |
            make k8sconfig            

      - run:
          name: Helm deploy
          shell: /bin/bash
          command: |
            make k8s-deploy


workflows:
  version: 2
  build-deploy:
    jobs:
      - build_push:
          context: GKE
      - install:
          requires:
           - build_push
          context: GKE